config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :site, only: [:index]
  root 'site#index'


  post '/current_location', to: 'locations#current_location'
  get '/search' => 'search#index'

  post 'truck/:id' => 'trucks#duplicate', as: :duplicate_truck

  resources :trucks do
    resources :locations
    resources :frequent_locations
  end
end

app/models/truck.rb
class Truck < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  include PgSearch

  pg_search_scope :search, against: [:name, :food_type],
    associated_against: { location: [:street_address, :street_address2, :city, :state, :zip]}

  belongs_to :user
  after_create :create_location
  has_one :location, dependent: :destroy
  has_many :frequent_locations
  validates :name, :twitter_handle, presence: true

  attr_accessor :address


  accepts_nested_attributes_for :frequent_locations, allow_destroy: true, reject_if: :has_blank_attributes

  private

  def create_location
    location = Location.new(truck_id: self.id, latitude: 0.0, longitude: 0.0)
    location.save
  end



end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  before_action :ensure_user_is_logged_in
  before_action :get_times, only: [:new, :edit]
  before_action :get_truck, only: [:show, :edit, :update, :destroy]

  def index
    # Truck.reindex
    # puts "++++++++++++++++++++++++++++++++"
    # trucks = Truck.search "Cupbop"
    # trucks.each do |truck|
    #   puts "================#{truck.name}"
    # end
    @trucks = current_user.trucks
  end

  def blah_trucks
    @trucks = current_user.truck
  end

  def show
  end

  def new
    @truck = Truck.new
  end

  def create
    @truck = Truck.new(truck_params)
    @truck.user_id = current_user.id
    if @truck.save
      flash[:notice] = "Truck saved successfully"
      redirect_to trucks_path
    else
      flash[:alert] = "Failed to save truck"
      render :new
    end
  end

  def edit
  end

  def update
    if @truck.update_attributes(truck_params)
      flash[:notice] = "Truck saved successfully"
      redirect_to trucks_path
    else
      flash[:alert] = "Failed to save truck"
      render :edit
    end
  end

  def destroy
    @truck = Truck.find(params[:id])
    @truck.destroy
    redirect_to trucks_path
  end


  private

  def truck_params
    params.require(:truck).permit(:name, :food_type, :user_id, :description, :starts_at, :ends_at, :image)
  end

  def ensure_user_is_logged_in
    redirect_to root_path unless current_user
  end

  def get_truck
    @truck = Truck.find(params[:id])
  end

  def get_times
    @times = TrucksHelper::times
  end
end

app/helpers/trucks_helper.rb
module TrucksHelper
 # Ruby logic. Yeah!
  def self.times
    times = []
    [*7..11].each {|i| times << "#{i}:00 am" << "#{i}:30 am"}

    times << "12:00 pm" << "12:30 pm"

    [*1..11].each {|i| times << "#{i}:00 pm" << "#{i}:30 pm"}

    times << "12:00 am" << "12:30 am"

    [*1..6].each {|i| times << "#{i}:00 am" << "#{i}:30 am"}

    times << 'Closed'

    times
  end

end

app/views/trucks/_truck_form.html.slim
= form_for @truck do |f|
  div class="form-group has-error"
    - if @truck.errors.any?
      ul
        - @truck.errors.full_messages.each do |error|
          li= error
  div class="form-group"
    = f.label :name
    br
    = f.text_field :name, placeholder: "Enter your truck's name", autofocus: true, class: "form-control"

  div class="form-group"
    = f.label :food_type
    br
    = f.text_area :food_type, placeholder: "Enter your food type", class: "form-control"

  div class="form-group"
    = f.label :description
    br
    = f.text_area :description, placeholder: "Description of your Noms truck", class: "form-control"

  div class="form-group"
    = f.label :website
    br
    = f.text_field :website, placeholder: 'URL to your site (e.g. "http://www.example.com")', class: "form-control"

  div class="form-group"
    =f.label :twitter_handle
    br
    =f.text_field :twitter_handle, placeholder: "Enter twitter handle without the @ symbol", class: "form-control"

  div class="form-group"
    h3 Payment Types
    = f.label :cash
    br
    =f.check_box :cash
    br
    = f.label :visa
    br
    = f.check_box :visa
    br
    = f.label :mastercard
    br
    = f.check_box :mastercard
    br
    = f.label :discover
    br
    = f.check_box :discover
    br
    = f.label :american_express
    br
    = f.check_box :american_express

  / .form-group
  /   = render "select_hours"

  div class="row"
    div class="col-md-3"
      div class="hour1"
        = f.label :monday_open
    div class="col-md-3"
      div class="work-day-open"
        = f.select(:monday_open, @times, class: "chosen-select")
    div class="col-md-3"
      div class="hour2"
        = f.label :monday_close
    div class="col-md-3"
      = f.select(:monday_close, @times)

  div class="row"
    div class="col-md-3"
      div class="hour1"
        = f.label :tuesday_open
    div class="col-md-3"
      div class="work-day-open"
        = f.select(:tuesday_open, @times, class: "chosen-select")
    div class="col-md-3"
      div class="hour2"
       = f.label :tuesday_close
    div class="col-md-3"
      = f.select(:tuesday_close, @times)

  div class="row"
    div class="col-md-3"
      div class="hour1"
        = f.label :wednesday_open
    div class="col-md-3"
      div class="work-day-open"
        = f.select(:wednesday_open, @times, class: "chosen-select")
    div class="col-md-3"
      div class="hour2"
        = f.label :wednesday_close
    div class="col-md-3"
      = f.select(:wednesday_close, @times)

  div class="row"
    div class="col-md-3"
      div class="hour1"
        = f.label :thursday_open
    div class="col-md-3"
      div class="work-day-open"
        = f.select(:thursday_open, @times, class: "chosen-select")
    div class="col-md-3"
      div class="hour2"
        = f.label :thursday_close
    div class="col-md-3"
      = f.select(:thursday_close, @times)

  div class="row"
    div class="col-md-3"
      div class="hour1"
        = f.label :friday_open
    div class="col-md-3"
      div class="work-day-open"
        = f.select(:friday_open, @times, class: "chosen-select")
    div class="col-md-3"
      div class="hour2"
        = f.label :friday_close
    div class="col-md-3"
      = f.select(:friday_close, @times)

  div class="row"
    div class="col-md-3"
      div class="hour1"
        = f.label :saturday_open
    div class="col-md-3"
      div class="work-day-open"
        = f.select(:saturday_open, @times, class: "chosen-select")
    div class="col-md-3"
      div class="hour2"
        = f.label :saturday_close
    div class="col-md-3"
      = f.select(:saturday_close, @times)

  div class="row"
    div class="col-md-3"
      div class="hour1"
        = f.label :sunday_open
    div class="col-md-3"
      div class="work-day-open"
        = f.select(:sunday_open, @times, class: "chosen-select")
    div class="col-md-3"
      div class="hour2"
        = f.label :sunday_close
    div class="col-md-3"
      = f.select(:sunday_close, @times)

  div class="row"
    div class="col-md-1"
      div class="hour1"
        .glyphicon.glyphicon-picture
    div class="col-md-3"
      = f.file_field :image

  div class="form-group"
    = f.submit "Submit Truck", class: "btn btn-primary submit"

app/views/trucks/_twitter_timeline.html.erb
<div class="twitter">
  <a class="twitter-timeline" href="https://twitter.com/mobilenoms" data-widget-id="488776111120068608" data-screen-name="<%= @truck.twitter_handle %>" data-show-replies="false"> Tweets by <%= @truck.name %></a>
</div>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/trucks/edit.html.slim
div class="row"
  div class="col-md-８ col-md-offset-２"
    h1 Edit Truck Info

    = render "truck_form"

  =link_to "Add Similar Truck", duplicate_truck_path(@truck), method: :post, class: "btn btn-success duplicate-truck"

app/views/trucks/index.html.slim
div class="row"
  div class="col-md-6"
    h1 My Trucks

  span class="col-md-6"
    = link_to( " Truck", new_truck_path, class: 'btn btn-danger glyphicon glyphicon-plus submit')

br

- @trucks.each do |truck|
  div class="row"
      div class="row"
        div class="col-md-2"
          = image_tag(truck.image.url(:logosm))
        div class="col-md-3"
          .name-index
            = link_to( truck.name, truck_path(truck.id))
        div class="col-md-6"
          = link_to edit_truck_path(truck.id)
            .btn.btn-default
              .glyphicon.glyphicon-pencil
          | &nbsp;&nbsp;

          = link_to truck_path(truck.id), method: :delete, data: { confirm: "Are you sure to delete this truck?"}
            .btn.btn-danger.truck-delete
              .glyphicon.glyphicon-trash

          | &nbsp;&nbsp;
          / Geocodes location
          a.geolocate-truck href="#" data-truck="#{truck.id}" data-location="#{truck.location.id}"
            span.btn.btn-success
              i.glyphicon.glyphicon-pushpin


          | &nbsp;&nbsp;
          / need a link to edit_truck_location path for manual update
          span.btn.btn-default
            = link_to("Edit Location", edit_truck_location_path(truck.id, truck.location))

        br
        br

app/views/trucks/index.slim
h1 My Trucks Index Page

app/views/trucks/new.html.slim
div class="row"
  div class="col-md-８ col-md-offset-２"
    h2 Add a Noms Truck

    = render "truck_form"

app/views/trucks/show.html.slim
div class="row"
  div class="col-md-12"
    .row
      div class="col-md-5"
        h1 = link_to @truck.name.titleize, @truck.website
        = image_tag(@truck.image.url(:logo))
        / div class="page-header"
        /   = @truck.name
        br
        br
        div class="food-type"
          = @truck.food_type

        div class="food-description"
          | "
          = @truck.description
          | "
          br
        div class="food-type"
          = link_to(image_tag("yelp.png"), @yelp_url)

        div class="food-description"
          = @yelp_snippet
          = image_tag(@yelp_image)
        div class="row"
          div class="col-md-4"
            div class="work_day"
              |Monday: &nbsp;
          div class="col-md-4"
            li  = @truck.monday_open
          div class="col-md-4"
            li  = @truck.monday_close
          br
          div class="col-md-4"
            div class="work_day"
              |Tuesday: &nbsp;
          div class="col-md-4"
            li  = @truck.tuesday_open
          div class="col-md-4"
            li  = @truck.tuesday_close
          br
          div class="col-md-4"
            div class="work_day"
              |Wednesday:
          div class="col-md-4"
            li  = @truck.wednesday_open
          div class="col-md-4"
            li  = @truck.wednesday_close
          br
          div class="col-md-4"
            div class="work_day"
              |Thursday: &nbsp;
          div class="col-md-4"
            li  = @truck.thursday_open
          div class="col-md-4"
            li  = @truck.thursday_close
          br
          div class="col-md-4"
            div class="work_day"
              |Friday: &nbsp;
          div class="col-md-4"
            li  = @truck.friday_open
          div class="col-md-4"
            li  = @truck.friday_close
          br
          div class="col-md-4"
            div class="work_day"
              |Saturday: &nbsp;
          div class="col-md-4"
            li  = @truck.saturday_open
          div class="col-md-4"
            li  = @truck.saturday_close
          br
          div class="col-md-4"
            div class="work_day"
              |Sunday: &nbsp;
          div class="col-md-4"
            li  = @truck.sunday_open
          div class="col-md-4"
            li  = @truck.sunday_close
          br
          br
        div class="row"
          div class="col-md-4"
            div class="pay"
              |Payment Type:
          .col-md-8
            div class="payment-type"
              - if @truck.cash
                = image_tag "money.png"
              - if @truck.visa
                = image_tag "visa.png"
              - if @truck.mastercard
                = image_tag "master.png"
              - if @truck.discover
                = image_tag "discover.png"
              - if @truck.american_express
                = image_tag "amex.png"

          br
          br

      .col-md-7.twitter-feed
        = render 'twitter_timeline'


  #truck-map data-truck="#{@truck.id}" data-location="#{@truck.location.id}"
  img href='<%= @search.name %>'