config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :site, only: [:index]
  root 'site#index'


  post '/current_location', to: 'locations#current_location'
  get '/search' => 'search#index'

  post 'truck/:id' => 'trucks#duplicate', as: :duplicate_truck

  resources :trucks do
    resources :locations
    resources :frequent_locations
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  include Searching

  def index
    @title = 'Home'
    trucks = Truck.all
    @trucks = trucks_in_range(trucks, 20).compact
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/_mailchimp.html.slim
label style="color: #08BDBD; font-size: 20px; font-weight: 400;" for="mce-EMAIL" Sign up for coupons!
br
form action="//mobilenoms.us8.list-manage.com/subscribe/post?u=3c2b30147782cf5270b07a6c1&amp;id=9cc52584e2" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate=""
  .input-group.add-on
    input.form-control type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Enter your email address"
    div style="position: absolute; left: -5000px;"
      input type="text" name="b_3c2b30147782cf5270b07a6c1_9cc52584e2" tabindex="-1" value=""
    br
    div.input-group-btn
      button#mc-embedded-subscribe type="submit" value="Subscribe" name="subscribe" class="btn btn-success mailchimp-button" Subscribe

app/views/site/_search.html.slim
div class='form-group' role="search"
  = form_tag search_path, method: :get do
    div.input-group.add-on
      = text_field_tag :q, '', placeholder: "Food type, truck name, location...", autofocus: true, class: 'form-control'
      div.input-group-btn
        = button_tag type: 'submit', class: 'btn btn-primary' do
          i.glyphicon.glyphicon-search
          | Search
    br
    span.within Within
    select name="distance"
      option value="5" 5 miles
      option value="10" 10 miles
      option value="15" 15 miles
      option value="20" 20 miles
      option value="25" 25 miles

app/views/site/index.html.slim
.btn.btn-success#find-yourself Use Current Location




div class='form_inline' role="form"
  =render 'search'

br
div class="form-group"
  = render 'mailchimp'

div class="logolg"
  div class="col-md-4 col-md-offset-4"
  -if user_signed_in?
    = link_to(image_tag("default_logolg.png", id: "main"), trucks_path, class: 'img-responsive')
  -else
    = link_to(image_tag("default_logolg.png", id: "main"), new_user_session_path, class: 'img-responsive')

div id="city-trucks-map"