config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :site, only: [:index]
  root 'site#index'


  post '/current_location', to: 'locations#current_location'
  get '/search' => 'search#index'

  post 'truck/:id' => 'trucks#duplicate', as: :duplicate_truck

  resources :trucks do
    resources :locations
    resources :frequent_locations
  end
end

app/models/location.rb
class Location < ActiveRecord::Base

  belongs_to :truck
  validates :truck_id, presence: true
  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode, if: :coordinates_changed?
  after_validation :geocode, if: :address_changed?


  private

  def address_changed?
    (changed & ["address"]).any?
  end

  def coordinates_changed?
    (changed & ["latitude", "longitude"]).any?
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  respond_to :html, :json
  before_action :get_location, only: [:show, :edit, :update]
  before_action :get_truck, only: [:edit]

  def show
  end

  def edit
   @frequent_location = @location.truck.frequent_locations
   @title = 'Edit Location'
  end

  def update
    respond_to do |format|
      if @location.update_attributes(location_params)
        format.html { redirect_to trucks_path }
        format.json{ render json: @location}
      end
    end
  end

  def current_location
    session[:latitude] = location_params[:latitude]
    session[:longitude] = location_params[:longitude]
    render json: session[:latitude]
  end

  private

  def location_params
    params.require(:location).permit(:address, :latitude, :longitude)
  end

  def get_location
    @location = Location.find(params[:id]) 
  end

  def get_truck
   @truck = Truck.find(params[:truck_id])
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/edit.html.slim
h1 Update Truck Location


/ = select_tag

= form_for [@location.truck, @location] do |f|
  .form-group
    = f.label :address
    = f.text_field :address, placeholder: "Street, City, State, Zip", class: "form-control", id: "address-field"
    = f.submit "Save Address", class: "btn btn-primary"

br

h4 Select from frequent locations

= select_tag "frequent_locations", options_for_select(@truck.frequent_locations.collect {|fl| fl.address}), id: "fl-select", class: "form-control"

btn.btn.btn-success.submit#fl Update Field
br
= link_to("Add Frequent Location", new_truck_frequent_location_path(@location.truck.id), class: 'btn btn-success submit')